---
# deploy-xos-sona-playbook.yml
# This playbook is used for development.  It walks through CORD's
# fetch -> build -> deploy container pipeline for XOS.
- name: Include vars
  hosts: all
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - "profile_manifests/{{ cord_profile }}.yml"
        - profile_manifests/local_vars.yml
# for docker, docker-compose
- include: devel-tools-playbook.yml
# pull / build base XOS images
- include: ../../orchestration/xos/pull-xos-playbook.yml
- include: ../../orchestration/xos/build-xos-playbook.yml
# build XOS core
- include: build-platform-install-playbook.yml
- include: cord-config-playbook.yml
- name: Pull other docker images if not present
  hosts: head
  roles:
    - pull-xos-docker-images
 
## andrew: You have to run build-lbaas-image.yml
- include: build-lbaas-image.yml
 
- include: launch-xos-playbook.yml
