---
- name: Include vars
  hosts: all
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - "profile_manifests/{{ cord_profile }}.yml"
        - profile_manifests/local_vars.yml
- name: Pull other docker images if not present
  hosts: head
  roles:
    - ssh-pki
    - ssh-install
    - copy-credentials
